# SOPS configuration file
keys:
  # User keys
  - &user_callum age1z2z3q49dq0f5e8wwfyal7gx2yhmghdg8g3pz5g8ltjmf0grvlsfqh3ealw

  # Machine-specific keys
  - &machine_titan  age1aydhplzpjeskpnvadsw6s3dyet7cqusxxjsse4g8hy0adf3pnptqk82yct
  - &machine_dione  age1mfy229e0yarwkz0kv4mpz4mwd4p9p68nwmqkm9ncqwvwx3thcfhs6w3end
  - &machine_elara  age1w8daf3cdy7a60l60a4uvszmrnj5q4yl6mm6ftdlkgw55rgcztejsxehng7
  - &machine_wsl    age12h6skcr40mmd5qegy5ygluc3qe8nkfc7c6gdx59l649h6uk7hpcsryeljw
  - &machine_phobos age102yywvgd50d8c5xamkyj8kva7ldqyl8r6rlsefd548nwjatajq7sv2pxqa

creation_rules:
  # Common machine secrets
  - path_regex: machines/common\.yaml$
    key_groups:
      - age:
          - *machine_titan
          - *machine_dione
          - *machine_elara
          - *machine_wsl
          - *machine_phobos

  # Machine specific secrets
  - path_regex: machines/titan/secrets\.yaml$
    key_groups:
      - age:
          - *machine_titan

  - path_regex: machines/dione/secrets\.yaml$
    key_groups:
      - age:
          - *machine_dione

  - path_regex: machines/elara/secrets\.yaml$
    key_groups:
      - age:
          - *machine_elara

  - path_regex: machines/wsl/secrets\.yaml$
    key_groups:
      - age:
          - *machine_wsl

  - path_regex: machines/phobos/secrets\.yaml$
    key_groups:
      - age:
          - *machine_phobos

  # Callum specific secrets
  - path_regex: users/callum/secrets\.yaml$
    key_groups:
      - age:
          - *user_callum

  # Callum SSH Keys
  - path_regex: users/callum/ssh/titan\.yaml$
    key_groups:
      - age:
        - *user_callum

      - age:
        - *machine_titan

  - path_regex: users/callum/ssh/dione\.yaml$
    key_groups:
      - age:
        - *user_callum

      - age:
        - *machine_dione

  - path_regex: users/callum/ssh/elara\.yaml$
    key_groups:
      - age:
        - *user_callum

      - age:
        - *machine_elara

  - path_regex: users/callum/ssh/wsl\.yaml$
    key_groups:
      - age:
        - *user_callum

      - age:
        - *machine_wsl

  - path_regex: users/callum/ssh/phobos\.yaml$
    key_groups:
      - age:
        - *user_callum

      - age:
        - *machine_phobos
