# SOPS configuration file
keys:
  # User keys
  - &user_callum age14nsdgefcjkanj2f6lj52wkcfl7424add5jx5zteynsw2xmxy89yq7anpqz

  # Device-specific keys
  - &device_titan age1t33cad4d9cdnkzj8t63l3w0qa6huue8c7gkqzv3ntsxlg7sdkqkqy4eaz0
  - &device_dione age1jup6qa4wxnl6aj6fuhw0fly5wkmjxa5r5drp0sejxvp7dlwpqa7qvlprmy

creation_rules:
  # Global secrets accessible by all devices and user
  - path_regex: secrets/secrets\.yaml$
    key_groups:
    - age:
      - *device_titan
      - *device_dione
      - *user_callum

  # Device-specific secrets
  - path_regex: secrets/devices/titan\.yaml$
    key_groups:
    - age:
      - *device_titan
      - *user_callum

  - path_regex: secrets/devices/dione\.yaml$
    key_groups:
    - age:
      - *device_dione
      - *user_callum
