# SOPS configuration file
keys:
  # User keys
  - &user_callum age1z2z3q49dq0f5e8wwfyal7gx2yhmghdg8g3pz5g8ltjmf0grvlsfqh3ealw

  # Machine-specific keys
  - &machine_titan  age1t33cad4d9cdnkzj8t63l3w0qa6huue8c7gkqzv3ntsxlg7sdkqkqy4eaz0
  - &machine_dione  age1mfy229e0yarwkz0kv4mpz4mwd4p9p68nwmqkm9ncqwvwx3thcfhs6w3end
  - &machine_elara  age1w8daf3cdy7a60l60a4uvszmrnj5q4yl6mm6ftdlkgw55rgcztejsxehng7
  - &machine_wsl    age12h6skcr40mmd5qegy5ygluc3qe8nkfc7c6gdx59l649h6uk7hpcsryeljw
  - &machine_phobos age1cux7ysh7nvrw3x8qaazxgtqu4fv79mdr23chq7z99pnmt0k5xeks8e6j5w

creation_rules:
  # Global secrets accessible by all machines and user
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *machine_titan
          - *machine_dione
          - *machine_elara
          - *machine_wsl
          - *machine_phobos
          - *user_callum

  # Machine-specific SSH keys (only accessible by that machine and user)
  - path_regex: machines/titan/ssh\.yaml$
    key_groups:
      - age:
          - *machine_titan
          - *user_callum

  - path_regex: machines/dione/ssh\.yaml$
    key_groups:
      - age:
          - *machine_dione
          - *user_callum

  - path_regex: machines/elara/ssh\.yaml$
    key_groups:
      - age:
          - *machine_elara
          - *user_callum

  - path_regex: machines/wsl/ssh\.yaml$
    key_groups:
      - age:
          - *machine_wsl
          - *user_callum

  - path_regex: machines/phobos/ssh\.yaml$
    key_groups:
      - age:
          - *machine_phobos
          - *user_callum

  # Machine-specific general secrets
  - path_regex: machines/.*/secrets\.yaml$
    key_groups:
      - age:
          - *machine_titan
          - *machine_dione
          - *machine_elara
          - *machine_wsl
          - *machine_phobos
          - *user_callum

  # SSH known hosts (accessible by all)
  - path_regex: ssh/.*\.yaml$
    key_groups:
      - age:
          - *machine_titan
          - *machine_dione
          - *machine_elara
          - *machine_wsl
          - *user_callum

